# wbmg_schema.schema.yml
# Version: 0.1.5

sermon:
  label: 'Sermon Schema'
  required:
    - title
    - field_date
    - field_speaker
  optional:
    - field_scripture
    - field_tags
  multi_value:
    - field_tags
